create table if not exists public.subscriptions (
 id bigint generated by default as identity primary key,
 user_id uuid not null,
 provider text not null default 'razorpay',
 provider_subscription_id text unique,
 status text not null default 'inactive',
 plan_code text not null default 'monthly_100',
 amount_inr integer not null default 100,
 current_period_start timestamptz,
 current_period_end timestamptz,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
alter table public.subscriptions enable row level security;
create policy "users_read_own_subscription" on public.subscriptions for select to authenticated using (auth.uid() = user_id);
